#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Auteur(s) : Maxime Mawait
# This file is part of INGInious
import os
import subprocess
import shlex
from inginious import feedback
from inginious import input


if __name__ == "__main__":
    os.chdir("student")
    input.parse_template("ijk.py")

    p = subprocess.Popen(shlex.split("python3 jsj.py"), stderr=subprocess.STDOUT, stdout=subprocess.PIPE)
    make_output = p.communicate()[0].decode('utf-8')

    if p.returncode:
        feedback.set_global_result("failed")
        feedback.set_global_feedback("Your code could not be executed. Please contact the course administrator.")
        exit(0)
    elif make_output == "20\n":
        feedback.set_global_result("success")
        feedback.set_global_feedback("Vous avez résolu l'exercice.")
    else:
        feedback.set_global_result("failed")
        feedback.set_global_feedback("Your code prints: " + make_output)