accessible: true
author: Aurélie MASSART, Alexandre KÜHN & Hua Yang HU
context: |
    Soit une liste d'entiers doublement chainée triée en ordre croissant. La liste est implémentée par la classe Node décrite comme :

    .. code-block:: java

        public class Node{
            int value;
            Node next;
            Node previous;

            ...
        }

    où next représente le Node suivant dans la liste et previous représente le Node précédent.
    On veut retourner la valeur de l'élément minimum de la liste. Indiquez le fragment de code nécessaire pour réaliser cette opération.
environment: java7
evaluate: best
groups: false
limits:
    memory: '200'
    output: '2'
name: 'Mission 11 : Question 08 : Question intermédiaire 1 - Minimum d''une liste triée'
network_grading: false
order: 10
problems:
    q1:
        header: |-
            Écrivez ici le fragment de code retournant le minimum de la liste triée. Voici les spécifications et la signature de la méthode à implémenter. Dans votre réponse, ne fournissez que les lignes de code internes à la fonction mais ne recopier pas la signature de la fonction. Faites attention à ne pas modifier dans votre fonction la liste donnée en argument. Attention à utiliser la programmation défensive pour vérifier les préconditions.

            .. code-block:: java

                /*
                 * @pre n != null
                 * @post retourne le minimum de la liste doublement chainée triée n
                 */
                public static int minimum(Node n){
                    //à compléter
                }
        language: Java
        name: Trouver le minimum d'une liste
        type: code
stored_submissions: 0
submission_limit:
    amount: -1
    period: -1
weight: 1.0
