accessible: true
author: Aurélie MASSART, Alexandre KÜHN & Hua Yang HU
context: |+
    Soit une implémentation d'une liste **simplement chaînée** et **triée** utilisant les classes ``SNode`` et ``SList`` suivantes :

    .. code-block:: java

        public class SList {
            public SNode first;

            public SList() {
                this.first = null; // empty list
            }
        }

        public class SNode {
            public int value;
            public SNode next;

            public SNode(int v) {
                this.value = v;
                this.next = null;
            }
        }

    Nous vous demandons d'ajouter une méthode ``removeDuplicates`` dans ``SList`` avec les spécifications suivantes :

    .. code-block:: java

        /*
         * @pre:  /
         * @post: La liste courante est modifiée:
         *        - La liste courante ne contient jamais
         *          deux noeuds avec la même valeur;
         *        - La liste reste triée;
         */
        public void removeDuplicates()

    Par exemple, supposons que vous avons la liste ``SList`` **sl** suivante :

    ``sl: snode(value: 10) -> node(value: 20) -> node(value: 20) -> node(value: 30) -> node(value: 30)``

    Le résultat de ``sl.removeDuplicates()`` est une modification de ``sl`` :

    ``sl: snode(value: 10) -> snode(value: 20) -> snode(value: 30)``

    .. image:: OWM11_23/RemoveDuplicates.png
        :height: 587px
        :width: 1197px
        :scale: 60%

    Le code que vous écrivez sera inséré à la zone commentée ci-dessous :

    .. code-block:: java
            
        public class SList {
            public SNode first;

            public SList() {
                this.first = null;
            }

            public void removeDuplicates() {
                /* votre code */
            }

        }

        public SNode(int v) {
            this.value = v;
            this.next = null;
        }

environment: java7
groups: false
limits:
    memory: '200'
    time: '30'
    output: '2'
name: 'Mission 11 : Question 16 : RemoveDuplicates de liste'
network_grading: false
order: 23
problems:
    q1:
        language: Java
        type: code
        name: RemoveDuplicates de liste
        header: 'Insérez le code que vous voulez ajouter dans la classe ``SList``, comme indiqué à la fin de l''énoncé ci-dessus.'

weight: 1.0
