accessible: true
author: Aurélie MASSART, Alexandre KÜHN & Hua Yang HU
context: |-
    Le but de cet exercice est d'ajouter un noeud au milieu d'une liste doublement chainée. Concrètement, vous devez insérer un noeud nommé NewNode et ayant comme valeur 3 entre les noeuds ayant les valeurs 2 et 4 dans la liste doublement chainée illustrée ci-dessous.

    .. image:: OWM11_7/Fin.png
        :height: 367px
        :width: 1065px
        :scale: 60%

    La liste doublement chainée est implémentée par la classe Node dont le code est fourni ci-dessous:

    .. code-block:: java

        public class Node{
            int value;
            Node next;
            Node previous;

            ...
        }

    Cette liste est donc telle que p.value = 1.

    Parmi les différentes propositions, une ou plusieurs est (sont) correcte(s). Cochez la (les) propositions correctes.
environment: default
groups: false
limits:
    memory: '32'
    output: '1024'
    time: '60'
name: 'Mission 11 : Question de démarrage 6 : Insertion d''un élément au milieu d''une
    liste doublement chainée'
network_grading: false
order: 7
problems:
    idFirstExercice:
        choices:
        -   text: |-
                .. code-block:: java

                    NewNode.next = p.next.next;
                    NewNode.previous = p.next;
                    p.next.next = NewNode;
                    p.next.next.previous = NewNode;
        -   text: |-
                .. code-block:: java

                    p.next.next.previous = NewNode;
                    p.next.next = NewNode;
            feedback: 'Ce fragment de code est erronné : le NewNode ne pointe pas
                correctement vers le noeud précédent et suivant dans la liste.'
        -   text: |-
                .. code-block:: java

                    NewNode.next = p.next;
                    NewNode.previous = p;
                    p.next.previous = NewNode;
                    p.next = NewNode;
            feedback: 'Ce fragment de code est erronné : le NewNode est inseré entre
                les éléments 1 et 2 et pas entre les éléments 2 et 4.'
        -   feedback: 'Ce fragment de code est erronné : la troisième ligne ne place
                pas le NewNode au bon endroit dans la liste.'
            text: |-
                .. code-block:: java

                    NewNode.next = p.next.next;
                    NewNode.previous = p.next;
                    p.next.previous = NewNode;
                    p.next.next = NewNode;
        -   valid: true
            text: |-
                .. code-block:: java

                    NewNode.next = p.next.next;
                    NewNode.previous = p.next;
                    p.next.next.previous = NewNode;
                    p.next.next = NewNode;
        header: ''
        error_message: '``You failed!!!``... '
        type: multiple-choice
        limit: 5
        name: Insertion d'un élément au milieu de la liste
weight: 1.0
