accessible: true
author: Lucas Ody & Tom Rousseaux 
context: |-
    Les coefficients d'une équation de 3ème degré vous sont donnés. A vous d'en trouver une des solutions entières, qui se trouve entre 0 et 20 inclus, en utilisant une boucle pour tester ces possibilités. Stockez votre réponse dans la variable ``r``.


    .. code-block:: java

        int r = 0; //La variable contenant la reponse du probleme
environment: java7
groups: false
limits:
    memory: '100'
    time: '30'
    output: '2'
name: 'Mission 1 : Solution d''une équation'
network_grading: false
order: 2
problems:
    q1:
        language: java
        type: code
        name: solution de l'équation
        header: ''
weight: 1.0
