#!/bin/bash
#   Copyright (c) 2015, 2016 François Michel, Clémentine Munyabarenzi
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.




#	@author: François MICHEL


# Ce script est un template pour lancer les exercices sur INGINIOUS.
# Ce script va compiler et exécuter les fichiers suivants :
# {EXERCICE}.java, 
# {EXERCICE}Vide.java
# {EXERCICE}Stu.java (qui sera créé par ce script) 
# et optionnellement {EXERCICE}Corr.java
# Ce script va parser le fichier {EXERCICE}Vide.java pour insérer la réponse de l'étudiant
# à l'intérieur et mettre le tout dans un fichier nommé {EXERCICE}Stu.java
# Il est important de bien respecter les noms des fichiers !

# Le fichier {EXERCICE}.java contiendra la main qui lancera les tests. Losque les tests ont réussi, la main se termine avec System.exit(127). Lorsqu'un problème survient, la main se termine avec une autre valeur que 127.

# Le fichier {EXERCICE}Vide.java contient un template java avec le code à compléter par l'étudiant.

# Le fichier {EXERCICE}Corr.java est un fichier java optionnel, sensé contenir une résolution correcte de l'exercice dans le cas où il serait utile de comparer les réponses renvoyées par le code de l'étudiant avec celles renvoyées par la fonction correcte, pour le feedback.

# Le fichiers custom.sh est un fichier optionnel, qui contient un script sh pour par exemple procéder à des vérifications dans le code (comme détecter l'utilisation de Math.pow à un endroit on on ne pourrait pas l'utiliser). Ce script doit renvoyer 0 (avec echo, par exemple), lorsque l'exécution du script s'est bien déroulée. Il doit renvoyer une autre valeur quand un probème est survenu (par exemple, on a détecté l'utilisation de Math.pow alors que c'est interdit). Lorsqu'un problème est survenu, le script doit retourner un feedback négatif pour la question en cours ainsi qu'un feedback négatif pour la tâche. Lorsqu'une erreur est survenue dans custom.sh, ce script-ci arrêtera automatiquement sa propre exécution directement avec exit, une fois custom.sh terminé.

# Pour utiliser ce script pour corriger plusieurs exercices en une seule tâche, il faut respecter des conventions. Tout d'abord, le premier exercice doit s'appeler q1, le second doit s'appeler q2, le ième doit s'appeler qi.
# Pour pourvoir faire un feedback spécialisé par exercice de la tâche, il faut impérativement que les erreurs (lorsque le code n'est pas correct) soient afficheées sur System.err avec comme première ligne une ligne qui comprend "Question i :" (pour le ième exercice). Par exemple :


# Sur System.err : 
# in testMethode : Question 1 : 
# la réponse obtenue n'est pas correcte
# in testMethode2 : Question 1 :
# la réponse obtenue vaut null mais ce ne devrait pas être le cas
# in testMethodeEx2 : Question 2 :
# assertequals : la réponse devrait valoir 3
# Question 2 : 
# une ArrayIndexOutOfBounds s'est lancée

# ... etc

# L'ordre des labels "Question i :" n'a pas d'importance, les messages peuvent être désordonnés et s'entremêler par question.
# La ligne qui contient le label "Question i : " sera supprimée dans le feedback

# Pour utiliser ce template sur une de vos tâches, les variables à modifier sont :
# EXERCICE, qui contient l'identifiant de l'exercice. Cet identifiant doit se retrouver dans les noms de fichiers java comme indiqué ci-dessus.
# CORR, qui vaudra 0 lorsqu'il n'y a pas de fichier {EXERCICE}Corr.java à compiler. (Attention, mettre CORR à une autre valeur que 0 alors qu'il n'y a pas de fichier {EXERCICE}Corr.java provoquera une erreur de compilation.
# EXECCUSTOM, qui vaudra 0 lorsqu'il n'y a pas de script custom.sh à exécuter et une autre valeur quand il faut en exécuter un.
# NEXERCICES, qui indique le nombre d'exercices que comprend la tâche. Laisser à 1 s'il n'y a qu'un exercice dans la tâche (le cas idéal)

# Pour le reste du script, il n'y a rien à modifier sauf peut-être pour certains cas précis.



EXERCICE="M5BiFi"
CUSTOMSCRIPT="sh custom.sh"
CORR=0

# EXECCUSTOM vaut 0 si on n'exécute pas de script "custom" pour faire des vérifications supplémentaires
EXECCUSTOM=0
NEXERCICES=2
CODELITTERAL=".. code-block:: java\n\n"
JAVAC="javac -cp .:/usr/share/java/junit.jar:/usr/share/java/hamcrest-core.jar"
JAVA="run_student --time 20 java -ea -cp .:./student:/usr/share/java/junit.jar:/usr/share/java/hamcrest-core.jar"

# On met la machine en UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

# Parsing de l'exercice
parsetemplate -o student/${EXERCICE}Stu.java student/${EXERCICE}Vide.java

OUTCUSTOM=0
if [ $EXECCUSTOM -ne 0 ]; then
	OUTCUSTOM=$($CUSTOMSCRIPT)
fi

if [ $OUTCUSTOM -ne 0 ]; then
	exit
fi

# On compile la tâche et on récupère le résultat dans un fichier
${JAVAC} student/${EXERCICE}.java 2> logOther.out
${JAVAC} student/${EXERCICE}Stu.java 2> log.out


OUTPUT=$(cat log.out)

OUTCORR=""
if [ $CORR -ne 0 ]; then
	${JAVAC} student/${EXERCICE}Corr.java 2> logCorr.out
	OUTCORR=$(cat logCorr.out)
fi

OUTOTHER=$(cat logOther.out)
ERREURENSEIGNANT=0
MESSAGEENSEIGNANT=""
if [ "$OUTCORR" != "" ];	then
	# feedback n'aime pas les "\n", donc on contourne le probleme en l'écrivant dans un fichier puis en le lisant.
	# sed permet d'indenter chaque ligne de son input avec une tabulation
	OUTCORR=$(echo "$OUTCORR" | sed -e 's/^/\t/')
	ERREURENSEIGNANT=1
	MESSAGEENSEIGNANT="$OUTCORR"
fi

if [ "$OUTOTHER" != "" ];	then
	# feedback n'aime pas les "\n", donc on contourne le probleme en l'écrivant dans un fichier puis en le lisant.
	# sed permet d'indenter chaque ligne de son input avec une tabulation
	OUTOTHER=$(echo "$OUTOTHER" | sed -e 's/^/\t/' | sed 's/%/%%/g' )
	ERREURENSEIGNANT=1
	MESSAGEENSEIGNANT="${MESSAGEENSEIGNANT}\n$OUTOTHER"
fi

if [ $ERREURENSEIGNANT -ne 0 ];	then
	FEED=$(printf "Le programme ne compile pas: \n ${CODELITTERAL}$MESSAGEENSEIGNANT\n")
	feedback -r failed -f "$FEED"
	exit
fi

ERREUR=0


# Si le fichier est vide et qu'il n'y a donc pas d'erreur de compilation
if [ "$OUTPUT" = "" ]; then
	# On lance l'exercice 1
	OUTPUT=$(${JAVA} student/${EXERCICE} 2> err.txt)
	RESULTAT=$?
	echo $RESULTAT
	OUTERR=$(cat err.txt)
	# S'il y a des erreurs dans l'exécution du programme (écrites sur stderr)
	if [ $RESULTAT -eq 127 ]; then
		if [ $NEXERCICES -eq 1 ]; then
			feedback -i q1 -r success -f "Bravo, votre code est correct !"
		else
			j=1
			while [ $j -le $NEXERCICES ]
			do
				# On fait un feedbacl positif par question
				feedback -i q${j} -r success -f "Vous avez bien répondu à cette question"
				j=$(( $j + 1 ))
			done
		fi
	elif [ $RESULTAT -eq 253 ]; then
		feedback -r timeout -f "La limite de temps d'exécution de votre programme est dépassée"
		exit
	else
		# Sinon c'est que les tests ont échoué, le programme possède des erreurs.
		if [ $NEXERCICES -eq 1 ]; then
			# feedback n'aime pas les "\n", donc on contourne le probleme en l'écrivant dans un fichier puis en le lisant.
			OUTERR=$(echo "$OUTERR" | sed -e 's/^/\t/' | sed 's/%/%%/g' )
			FEED=$(printf "Il semble que vous ayiez fait des erreurs dans votre code...\n ${CODELITTERAL}$OUTERR\n")
			feedback -i q1 -r failed -f "$FEED"
			ERREUR=1
		else
			i=1
			while [ $i -le $NEXERCICES ]
			do
				# On récupère un feedback par question dans le System.err, en suivant le format imposé par convention
				OUTERRPARQUESTION=$(echo "$OUTERR" | sed -e "/Question $i :/,/Question [^\D1] :/!d" | grep -v -E "Question [0-9] :")
				if [ "$OUTERRPARQUESTION" == "" ]; then
					feedback -i q${i} -r success -f "Vous avez bien répondu à cette question"
				else
					OUTERRPARQUESTION=$(echo "$OUTERRPARQUESTION" | sed -e 's/^/\t/' | sed 's/%/%%/g' )
					FEED=$(printf "Il semble que vous ayiez fait des erreurs dans votre code...\n ${CODELITTERAL}$OUTERRPARQUESTION\n")
					feedback -i q${i} -r failed -f "$FEED"
				fi
				i=$(( $i + 1 ))
			done
			ERREUR=1
		fi
	fi

	# On vérifie si la tâche s'est bien déroulée ou s'il y a eu un souci, et on fait un feedback de la tâche complète
	if [ $ERREUR -eq 0 ]; then
		feedback -r success -f "Bravo, votre code est correct !"
	else
		feedback -r failed -f "Vous n'avez pas réussi tous les exercices"
	fi
else
	# feedback n'aime pas les "\n", donc on contourne le probleme en l'écrivant dans un fichier puis en le lisant.
	# sed permet d'indenter chaque ligne de son input avec une tabulation
	OUTPUT=$(echo "$OUTPUT" | sed -e 's/^/\t/' | sed 's/%/%%/g' )
	FEED=$(printf "Votre programme ne compile pas: \n ${CODELITTERAL}$OUTPUT\n")
	feedback -r failed -f "$FEED"
fi



