accessible: true
author: Aurélie MASSART, Alexandre KÜHN & Hua Yang HU
context: |
    Soit un stack défini par la classe suivante :

    .. code-block:: java

        public class Node{
            int value;
            Node next;

            ...
        }

    .. code-block:: java

        public class Stack{
            Node first;

            ...
        }

    La classe Stack est incomplète : il manque les opérations push et pop ajoutant un élément et retirant un élément du stack. Complétez la classe Stack.
environment: java7
groups: false
limits:
    memory: '200'
    time: '30'
    output: '2'
name: 'Mission 11 : Question intermédiare 5 : Opérations sur un stack : implémentations'
network_grading: false
order: 14
problems:
    q1:
        language: java
        type: code
        name: Fonctions pop et push
        header: |
            Implémentez les fonctions pop et push d'un stack. Les signatures des fonctions sont fournies ci-dessous. Vous **devez** recopier la signature des fonctions dans votre réponse. On considère que la pile contient initialement au moins un élément.

            .. code-block:: java

                /*
                 * @pre le stack est non vide
                 * @post retire et retourne un element du stack
                 */
                public int pop();

                /*
                 * @pre -
                 * @post ajoute l'élément val dans le stack
                 */
                public void push(int val);
weight: 1.0
